# Generated by Django 4.2.6 on 2024-10-15 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_module', '0002_alter_user_options_remove_user_adress_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربران'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='user',
            name='mobile',
            field=models.CharField(max_length=12, null=True, verbose_name='شماره'),
        ),
        migrations.AddField(
            model_name='user',
            name='national_code',
            field=models.CharField(max_length=15, null=True, verbose_name='کدملی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
