# Generated by Django 4.2.6 on 2024-10-20 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_module', '0003_alter_user_options_remove_user_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/', verbose_name='عکس پروفایل'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='شماره'),
        ),
        migrations.AlterField(
            model_name='user',
            name='national_code',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='کدملی'),
        ),
    ]
