# Generated by Django 4.2.6 on 2024-10-20 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_module', '0004_user_profile_image_alter_user_mobile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='national_code',
        ),
    ]
