# Generated by Django 4.2.6 on 2024-11-16 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Category_Article_Module', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='articlecategory',
            index=models.Index(fields=['url_title'], name='Category_Ar_url_tit_86b755_idx'),
        ),
        migrations.AddIndex(
            model_name='articlecategory',
            index=models.Index(fields=['is_active'], name='Category_Ar_is_acti_3e85f2_idx'),
        ),
    ]
