# Generated by Django 4.2.6 on 2025-01-04 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product_module', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.FloatField(default=0, verbose_name='امتیاز'),
        ),
        migrations.AddField(
            model_name='product',
            name='review_count',
            field=models.IntegerField(default=0, verbose_name='تعداد نظرات'),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='کد محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Product_module.productcategory', verbose_name='دسته بندی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(db_index=True, default=1, verbose_name='توضیحات اصلی'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='images/products', verbose_name='تصویر اصلی'),
        ),
        migrations.CreateModel(
            name='ProductGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/products/gallery', verbose_name='تصویر')),
                ('is_main', models.BooleanField(default=False, verbose_name='تصویر اصلی')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product_module.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'تصویر گالری',
                'verbose_name_plural': 'گالری تصاویر',
            },
        ),
    ]
