# Generated by Django 4.2.6 on 2025-01-04 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product_module', '0005_product_rating_product_review_count_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='product',
            name='review_count',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
