# Generated by Django 4.2.6 on 2025-01-06 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_module', '0009_product_features_product_shipping_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_thumbnails',
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='موجودی'),
        ),
    ]
