# Generated by Django 4.2.6 on 2025-01-06 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_module', '0010_remove_product_image_thumbnails_product_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(related_name='products', to='Product_module.productcategory', verbose_name='دسته بندی\u200cها'),
        ),
    ]
