# Generated by Django 4.2.6 on 2024-11-16 18:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArticleModule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='reading_time',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='زمان مطالعه (دقیقه)'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['slug'], name='ArticleModu_slug_42a868_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['created_at'], name='ArticleModu_created_7c20b4_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['status', 'is_active'], name='ArticleModu_status_45b2fe_idx'),
        ),
    ]
