# Generated by Django 4.2.6 on 2025-01-14 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'آیتم سبد خرید', 'verbose_name_plural': 'آیتم های سبد خرید'},
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='cart',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='cart',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'در انتظار پرداخت'), ('SUCCESS', 'موفق'), ('FAILED', 'ناموفق'), ('CANCELED', 'لغو شده'), ('ERROR', 'خطا')], default='PENDING', max_length=10, verbose_name='وضعیت پرداخت'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رنگ'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='size',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='سایز'),
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='added_date',
        ),
    ]
