# Generated by Django 4.2.6 on 2024-10-08 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, verbose_name='نام و نام خانوادگی')),
                ('email', models.EmailField(max_length=200, verbose_name='ایمیل')),
                ('phone', models.CharField(max_length=12, verbose_name='شماره تماس')),
                ('text', models.TextField(verbose_name='توضیحات')),
                ('object', models.CharField(max_length=120, null=True, verbose_name='موضوع')),
            ],
        ),
    ]
